feat(odyssey-storybook): add odyssey-storybook private package
okta/odyssey pull request #1031
Opened 2021-08-11 19:30 UTC by jeffbelser-okta

Includes RTL toggle package for storybook as well

2021-08-11 21:06 UTC, arnoldsandoval-okta requested changes
We should update this line so we can continue to get CD for SB: https://github.com/okta/odyssey/blob/develop/.github/workflows/deployment.yml#L57

We should also move the [storybook build script](https://github.com/okta/odyssey/pull/1031/files#diff-0eb22a4d312e56c1ca00c7dd3a7e3a2e524734e89402b4c6cb18c3af9520235dR38) from odyssey-react to odyssey-storybook

2021-08-11 21:32 UTC, jeffbelser-okta commented
@arnoldsandoval-okta thanks for review - no need to make the change you're requesting there. The build script continues to work **through** `@okta/odyssey-react` by utilizing `@okta/odyssey-storybook` as a development dependency. [See the hosted site here](https://05b78be.ods.dev/sb/index.html?path=/story/welcome-introduction-readme--page)

 I don't think it would be as natural for us to structure the code such that we run the build script from a packaged consumed as a dependency targeting the dependent packages contents. Do you agree?

2021-08-11 21:52 UTC, edburyenegren-okta commented on packages/odyssey-storybook/package.json
> +    "@pxblue/storybook-rtl-addon": "^1.0.1",
🙏🏼

2021-08-11 21:53 UTC, edburyenegren-okta approved these changes
I'm good with the move + appreciate the RTL add. Saw @arnoldsandoval-okta has some questions re CD, but I trust y'all will find the best path.

2021-08-11 22:06 UTC, jeffbelser-okta commented
One of the "gotchas" with using TS here is that changes to the storybook preset will not only require bouncing the server (already the case) but also rebuilding the preset from source via `yarn prepare`, `yarn install` or similar

2021-08-12 17:38 UTC, arnoldsandoval-okta approved these changes

2021-08-12 18:02 UTC, merged