Clean up props
okta/odyssey pull request #1868
Opened 2023-07-07 19:20 UTC by jordankoschei-okta

Alphabetize and add documentation comments to props.

2023-07-11 19:20 UTC, edburyenegren-okta requested changes

2023-07-11 19:20 UTC, edburyenegren-okta commented on packages/odyssey-react-mui/src/Tooltip.tsx
> +  /**
These should be docced above in `TooltipProps`, right?

2023-07-12 18:12 UTC, KevinGhadyani-Okta commented on packages/odyssey-react-mui/src/Dialog.tsx
> +   * Callback that controls what happens when the Dialog is dismissed
```suggestion
   * Callback that controls what happens when the Dialog is dismissed.
```

2023-07-14 16:24 UTC, edburyenegren-okta approved these changes

2023-07-14 19:52 UTC, merged