[WIP] Tiles
okta/odyssey pull request #2004
Opened 2023-10-19 19:54 UTC by jordankoschei-okta

2023-10-27 18:24 UTC, KevinGhadyani-Okta commented on packages/odyssey-react-mui/src/Button.tsx
> +});
We can default this to `false`:

```suggestion
export type ButtonContextValue = {
  isFullWidth?: boolean;
};

export const ButtonContext = createContext<ButtonContextValue>({
  isFullWidth: false,
});
```

2023-10-27 18:25 UTC, KevinGhadyani-Okta commented on packages/odyssey-react-mui/src/Button.tsx
> +      isFullWidthProp,
This is missing `isFullWidth`.

2023-10-27 18:26 UTC, jordankoschei-okta commented on packages/odyssey-react-mui/src/MenuButton.tsx
> +    | ReactFragment
Add generic if possible

2023-10-27 18:27 UTC, KevinGhadyani-Okta commented on packages/odyssey-react-mui/src/MenuButton.tsx
> +  menuAlignment?: "left" | "right";
Don't these need to be in an array for Storybook?

2023-10-27 18:27 UTC, KevinGhadyani-Okta commented on packages/odyssey-react-mui/src/MenuButton.tsx
>    }, []);
Callback missing `onClose`.

2023-10-27 18:27 UTC, KevinGhadyani-Okta commented on packages/odyssey-react-mui/src/MenuButton.tsx
>    }, []);
Missing `onClose` in dependency arg.

2023-10-27 18:28 UTC, KevinGhadyani-Okta commented on packages/odyssey-react-mui/src/MenuButton.tsx
> +        transformOrigin={{ horizontal: menuAlignment, vertical: "top" }}
Can we memoize these values?

2023-10-27 18:37 UTC, KevinGhadyani-Okta commented on packages/odyssey-react-mui/src/Tile.tsx
> +    }
I wonder if we can change these to `never`?

2023-10-27 18:39 UTC, KevinGhadyani-Okta commented on packages/odyssey-react-mui/src/Tile.tsx
> +            }}
Can we `useMemo` these?

2023-10-27 18:40 UTC, KevinGhadyani-Okta commented on packages/odyssey-react-mui/src/Tile.tsx
> +            }}
Ideally, these styles would be part of the theme.

2023-10-27 18:40 UTC, KevinGhadyani-Okta commented on packages/odyssey-react-mui/src/Tile.tsx
> +            <ButtonContext.Provider value={{ isFullWidth: true }}>
Can we set this context at the top of the component above the function, so it's a static memory refrence?

`const buttonContextValue`.

2023-10-27 18:42 UTC, KevinGhadyani-Okta commented on packages/odyssey-react-mui/src/Tile.tsx
> +      {!onClick && cardContent}
This can be a ternary.

2023-10-27 18:42 UTC, KevinGhadyani-Okta commented on packages/odyssey-react-mui/src/Tile.tsx
> +            ariaLabel="Tile menu"
Can we modify this label?

2023-10-27 18:43 UTC, KevinGhadyani-Okta commented on packages/odyssey-react-mui/src/Tile.tsx
> +          }}
Can we memoize these?

2023-10-27 18:45 UTC, KevinGhadyani-Okta commented on packages/odyssey-react-mui/src/properties/ts/.ts.DS_Store
> +export const translation = {"\u0000\u0000\u0000\u0001Bud1\u0000\u0000\u0010\u0000\u0000\u0000\b\u0000\u0000\u0000\u0010\u0000\u0000\u0000\u0002":"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u000
Remove this file and add to `.gitignore`.

`git rm --cached packages/odyssey-react-mui/src/properties/ts/.ts.DS_Store`

2023-10-27 18:45 UTC, KevinGhadyani-Okta commented on packages/odyssey-react-mui/src/theme/components.tsx
> +          width: `calc(100% + (${odysseyTokens.Spacing5} * 2))`,
Let's add a ticket to fix this.

2023-10-27 18:46 UTC, KevinGhadyani-Okta commented on packages/odyssey-react-mui/src/theme/components.tsx
> +          },
Can this a direct child of the root?

`& > img`?

2023-10-27 18:47 UTC, KevinGhadyani-Okta commented on packages/odyssey-storybook/src/components/odyssey-labs/Tile/Tile.stories.tsx
> +const storybookMeta: Meta = {
```suggestion
const storybookMeta: Meta<TileProps> = {
```

2023-10-27 18:48 UTC, KevinGhadyani-Okta commented on packages/odyssey-storybook/src/components/odyssey-mui/MenuButton/MenuButton.stories.tsx
> +        },
"left" and "right" should be in an array/union type.

2023-10-27 18:49 UTC, KevinGhadyani-Okta requested changes
A bunch of small comments.

2024-01-19 20:55 UTC, jordankoschei-okta commented
Closing because this is stale and needs some serious rework

2024-01-19 20:55 UTC, closed without merging