Small style fixes to Link component
okta/odyssey pull request #2024
Opened 2023-10-31 18:58 UTC by bryancunningham-okta

[REPLACE_WITH_JIRA_TICKET_NUMBER](https://oktainc.atlassian.net/browse/REPLACE_WITH_JIRA_TICKET_NUMBER)

## Summary
- Remove `text-decoration: underline` on non-hovered default link style
- Remove some spacing between link text and icon

## Testing & Screenshots

- [ ] I have confirmed this change with my designer and the Odyssey Design Team.

2023-10-31 19:04 UTC, KevinGhadyani-Okta approved these changes
Looks good, but I wanna make sure these spacing values will suffice. Are these in Figma? Do we want an `&nbsp;`?

I thought we were adding underlines back to links for accessibility reasons like GitHub recently did?

2023-10-31 19:05 UTC, KevinGhadyani-Okta reviewed
Sorry, wanted to set this to "comment", not Approve.

2023-10-31 19:05 UTC, KevinGhadyani-Okta requested changes
Setting to Request Changes to remove the approval until we get more information from design.

2023-11-02 17:05 UTC, bryancunningham-okta commented
@KevinGhadyani-Okta I've got buy in from Design on this spacing. I think this is good to go

2023-11-02 17:13 UTC, KevinGhadyani-Okta approved these changes

2023-11-02 17:13 UTC, merged